
    name: string
    nickName: string
    pwd: string
    sex: string
    redBookId: number
    avatar: string
    location: string
    desc: string
}


    userName: string;
    avatarUrl: string;
    message: string;
    dateTime: string;
    location: string;
    favoriteCount: number;
    isFavorite: boolean;
    children?: ArticleComment[];
}


    id: number;
    title: string;
    desc: string;
    tag: string[];
    dateTime: string;
    location: string;
    userId: number;
    userName: string;
    isFollow: boolean;
    avatarUrl: string;
    images: string[];
    favoriteCount: number;
    collectionCount: number;
    isFavorite: boolean;
    isCollection: boolean;
    comments?: ArticleComment[];
    commentCount?: number;
}


    id: number;
    title: string;
    image: string;
    price: number;
    originPrice: number | undefined;
    promotion: string | undefined;
}


const MOCK_USERS = [
    {
        name: '13686561615',
        nickName: '深渊口香糖',
        pwd: '123456',
        sex: 'female',
        redBookId: 118302851,
        avatar: `/avatar/avatar_39.png`,
        location: '上海',
        desc: '偶尔喝点酒，夏天水里走',
    },
    {
        name: 'dagongjue',
        nickName: '深渊口香糖',
        pwd: '123456',
        sex: 'female',
        redBookId: 118302851,
        avatar: `/avatar/avatar_35.png`,
        location: '上海',
        desc: '偶尔喝点酒，夏天水里走',
    },
    {
        name: '18818818188',
        nickName: '尼古拉斯·张三',
        pwd: '888888',
        sex: 'male',
        redBookId: 118098706,
        avatar: `/avatar/avatar_02.png`,
        location: '北京',
        desc: '大家好，我是张三，我学习RN两年半了。',
    },
    {
        name: '18626668866',
        nickName: '赫尔墨斯·李四',
        pwd: '666666',
        sex: 'female',
        redBookId: 116903456,
        avatar: `/avatar/avatar_03.png`,
        location: '云南',
        desc: '大家好，我是李四，我喜欢唱歌、跳舞、打篮球。',
    },
]

const MOCK_ARTICLES = [
    // article 0 - Pitt第二季（来自真实XHS笔记）
    {
        id: 21,
        title: 'HBO王炸剧《匹兹堡医护前线》第二季今日上线❗',
        desc: '🎬︎剧集名称：《匹兹堡医护前线》第二季\n🔍︎创作类型：剧情\n📍制片国家/地区：美国\n👍推荐指数：🌟🌟🌟🌟🌟\n\n✅剧情简介：第二季的故事线设定在第一季惊心动魄的事件发生10个月后。诺亚·怀尔饰演的罗比医生再次带领团队面对极限挑战。在独立日周末的急诊高峰期，匹兹堡创伤医学中心遭遇了全系统计算机崩溃，迫使所有医护人员在极度混乱中回归"纯手动"模拟操作模式。',
        tag: ['匹兹堡医护前线', '匹兹堡医护前线第二季', 'ThePitt', '美剧推荐', 'NoahWyle', '医疗剧'],
        dateTime: '2025-06-09 10:00',
        location: '北京',
        userId: 1,
        userName: '美剧迷日记',
        isFollow: false,
        avatarUrl: '/avatar/avatar_05.png',
        images: [
            'http://ci.xiaohongshu.com/notes_pre_post/1040g3k831r2hk28l0a0g43roo8ubtkqq9ad7d6g?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/notes_pre_post/1040g3k831r2hk28l0a1043roo8ubtkqq5agkufo?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/notes_pre_post/1040g3k831r2hk28l0a1g43roo8ubtkqq1rupk40?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/notes_pre_post/1040g3k831r2hk28l0a2043roo8ubtkqq7qk2rhg?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/notes_pre_post/1040g3k831r2hk28l0a2g43roo8ubtkqqdeeb5q8?imageView2/2/w/1080/format/jpg',
        ],
        favoriteCount: 4521,
        collectionCount: 892,
        isFavorite: false,
        isCollection: false,
        comments: [
            {
                userName: '追剧小分队',
                avatarUrl: '/avatar/avatar_30.png',
                message: '不行，这剧必须一次性看完才能体验到那种窒息感',
                dateTime: '2025-06-09 12:30',
                location: '上海',
                favoriteCount: 75,
                isFavorite: false,
                children: [
                    {
                        userName: '急诊科小李',
                        avatarUrl: '/avatar/avatar_31.png',
                        message: '其实还好，感觉第二季大家都闲了很多，没第一季那么窒息',
                        dateTime: '2025-06-09 13:00',
                        location: '广东',
                        favoriteCount: 10,
                        isFavorite: false,
                    },
                ],
            },
            {
                userName: '剧荒求推荐',
                avatarUrl: '/avatar/avatar_32.png',
                message: '节奏太快了 看五分钟我就要歇一歇',
                dateTime: '2025-06-09 14:20',
                location: '浙江',
                favoriteCount: 37,
                isFavorite: false,
                children: [
                    {
                        userName: 'ADHD患者日常',
                        avatarUrl: '/avatar/avatar_33.png',
                        message: '我反而是看节奏慢的才会分心然后歇一歇刷下手机，这部就是一口气看下来',
                        dateTime: '2025-06-09 15:00',
                        location: '北京',
                        favoriteCount: 26,
                        isFavorite: false,
                    },
                ],
            },
            {
                userName: '低精力选手',
                avatarUrl: '/avatar/avatar_34.png',
                message: '低精力人群看完一集要歇半天才能缓回来',
                dateTime: '2025-06-09 16:00',
                location: '四川',
                favoriteCount: 6,
                isFavorite: false,
                children: null,
            },
            {
                userName: '编剧观察员',
                avatarUrl: '/avatar/avatar_35.png',
                message: '我感觉编剧是不是换了？节奏慢了且加入了一些自我感动但莫名其妙的剧情',
                dateTime: '2025-06-10 09:15',
                location: '江苏',
                favoriteCount: 111,
                isFavorite: false,
                children: [
                    {
                        userName: '美剧老炮儿',
                        avatarUrl: '/avatar/avatar_36.png',
                        message: '男主主编了 自恋得很 第一季是一个更大的编剧团队',
                        dateTime: '2025-06-10 10:00',
                        location: '上海',
                        favoriteCount: 131,
                        isFavorite: false,
                    },
                ],
            },
        ],
    },
    // article - 准爸爸待产攻略（来自真实XHS笔记 note-TKo, 126972赞）
    {
        id: 22,
        title: '老婆怀孕了🤰准爸爸能做什么❓快转给老公',
        desc: '应家人们的要求，这里给大家整理出打印版本的孕1月-10月准爸爸备忘录📝快转发给老公抄作业!\n\n✅孕一月到十月准爸爸备忘录\n✅提前熟悉去🏥的路线和环境\n✅熟悉待产包\n✅了解临产征兆(见红、破水、规律宫缩)\n✅提前了解护理知识了解顺产过程\n✅了解剖宫产的过程\n✅办理住院手续\n✅提前把家收拾干净\n✅做好住院期间饮食规律\n✅提前熟悉新生儿护理的方法',
        tag: ['准爸爸', '怀孕', '待产包', '孕期日常', '新生儿护理'],
        dateTime: '2025-11-15 18:30',
        location: '上海',
        userId: 2,
        userName: '奶爸成长记',
        isFollow: false,
        avatarUrl: '/avatar/avatar_08.png',
        images: [
            'http://ci.xiaohongshu.com/1040g2sg31dktmk0t10dg416qcqjlq8p68c0ak5g?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/1040g00831dktmk0vgs60416qcqjlq8p6rma3pa8?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/1040g2sg31dktmk100udg416qcqjlq8p60r4ug3g?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/1040g00831dktmk1i0u5g416qcqjlq8p6en0lpl8?imageView2/2/w/1080/format/jpg',
        ],
        favoriteCount: 19578,
        collectionCount: 12800,
        isFavorite: false,
        isCollection: false,
        comments: [
            {
                userName: '新手奶爸小林',
                avatarUrl: '/avatar/avatar_37.png',
                message: '求一份ppt，第一次当爸爸，怕有啥没注意到',
                dateTime: '2025-11-16 09:00',
                location: '北京',
                favoriteCount: 234,
                isFavorite: false,
                children: [
                    {
                        userName: '已经是二胎爸了',
                        avatarUrl: '/avatar/avatar_38.png',
                        message: '其实这些很简单的，做起来就知道了',
                        dateTime: '2025-11-16 10:30',
                        location: '广东',
                        favoriteCount: 18,
                        isFavorite: false,
                    },
                ],
            },
            {
                userName: '产科护士小何',
                avatarUrl: '/avatar/avatar_39.png',
                message: '太全面了！很多爸爸进产房前完全懵的，有这个清单好太多了',
                dateTime: '2025-11-16 14:20',
                location: '浙江',
                favoriteCount: 87,
                isFavorite: false,
                children: null,
            },
            {
                userName: '焦虑型准爸爸',
                avatarUrl: '/avatar/avatar_40.png',
                message: '虽然还没办婚礼，现在已经提前焦虑上了',
                dateTime: '2025-11-17 08:00',
                location: '江苏',
                favoriteCount: 156,
                isFavorite: false,
                children: [
                    {
                        userName: '过来人经验',
                        avatarUrl: '/avatar/avatar_41.png',
                        message: '有这种想法已经不错了 起码知道去看去学习',
                        dateTime: '2025-11-17 09:00',
                        location: '上海',
                        favoriteCount: 42,
                        isFavorite: false,
                    },
                ],
            },
        ],
    },
    // article 1 - 猫咪治愈（来自真实XHS笔记）
    {
        id: 1,
        title: '最幸福的事情是我拥有小猫，不止一只！！',
        desc: '每天回家都有小猫咪迎接，这就是幸福吧～',
        tag: ['猫咪', '治愈系', '萌宠', '猫咪日常'],
        dateTime: '2023-02-27 12:20',
        location: '广东',
        userId: 1,
        userName: '小飞飞爱猫咪',
        isFollow: false,
        avatarUrl: '/avatar/avatar_01.png',
        images: [
            'http://ci.xiaohongshu.com/spectrum/1040g0k031pr0a47ql4005p5og0ipenpivrjocmo?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/spectrum/1040g0k031pr0a47ql40g5p5og0ipenpi0s99q08?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/spectrum/1040g0k031pr0a47ql4105p5og0ipenpi3fk4j6o?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/spectrum/1040g0k031pr0a47ql41g5p5og0ipenpi32d2tjg?imageView2/2/w/1080/format/jpg',
        ],
        favoriteCount: 3258,
        collectionCount: 166,
        isFavorite: false,
        isCollection: false,
        comments: [
            {
                userName: '小AA呀',
                avatarUrl: '/avatar/avatar_40.png',
                message: '我的妈呀，太可爱了吧！',
                dateTime: '2023-02-28 07:23',
                location: '南宁',
                favoriteCount: 12,
                isFavorite: false,
                children: [
                    {
                        userName: '小飞飞爱猫咪',
                        avatarUrl: '/avatar/avatar_01.png',
                        message: '谢谢支持～',
                        dateTime: '2023-02-28 08:23',
                        location: '广东',
                        favoriteCount: 3,
                        isFavorite: false,
                    },
                ],
            },
            {
                userName: '天天甜甜',
                avatarUrl: '/avatar/avatar_39.png',
                message: '好可爱啊，好想养一只啊，这么萌的小猫咪是怎么养的啊，我要去up那里去买一只，快快告诉我怎么买？',
                dateTime: '2023-02-28 09:09',
                location: '福建',
                favoriteCount: 7,
                isFavorite: false,
                children: null,
            },
            {
                userName: 'Prince小小',
                avatarUrl: '/avatar/avatar_38.png',
                message: '伤过了，不会再相信爱情了。',
                dateTime: '2023-02-28 11:11',
                location: '河北',
                favoriteCount: 1,
                isFavorite: false,
                children: null,
            },
            {
                userName: '深海的蓝',
                avatarUrl: '/avatar/avatar_37.png',
                message: '真的好可爱啊，我要养一只',
                dateTime: '2023-02-28 11:34',
                location: '天津',
                favoriteCount: 1,
                isFavorite: false,
                children: null,
            },
            {
                userName: 'Look Ground',
                avatarUrl: '/avatar/avatar_36.png',
                message: '支持了',
                dateTime: '2023-02-28 11:35',
                location: '南京',
                favoriteCount: 0,
                isFavorite: false,
                children: null,
            },
        ],
    },
    // article 2 - 家常菜（来自真实XHS笔记）
    {
        id: 2,
        title: '新手秒变大厨的16道家常菜合集‼️马住',
        desc: '整理了16道超简单的家常菜，新手也能轻松上手！\n每一道都是家人夸赞的味道，赶紧收藏起来～',
        tag: ['家常菜', '食谱', '做饭', '新手厨房', '下饭菜'],
        dateTime: '2023-02-28 09:21',
        location: '广西',
        userId: 2,
        userName: '大厨师小飞象',
        isFollow: false,
        avatarUrl: '/avatar/avatar_02.png',
        images: [
            'http://ci.xiaohongshu.com/1040g0083168qikev0u005nh2pe6g8q82qbc0clo?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/1040g0083168qikev0u0g5nh2pe6g8q82n480ca8?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/1040g0083168qikev0u105nh2pe6g8q82mki3iq8?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/1040g0083168qikev0u1g5nh2pe6g8q829ckntrg?imageView2/2/w/1080/format/jpg',
        ],
        favoriteCount: 10982,
        collectionCount: 208,
        isFavorite: false,
        isCollection: false,
        comments: [
            {
                userName: '胖胖胖',
                avatarUrl: '/avatar/avatar_40.png',
                message: '果断关注，这个博主做的菜真实色香味俱全。每天跟着学做菜，我要做大厨了，啊哈哈～',
                dateTime: '2023-02-28 07:23',
                location: '成都',
                favoriteCount: 45,
                isFavorite: false,
                children: [
                    {
                        userName: '小飞飞爱猫咪',
                        avatarUrl: '/avatar/avatar_01.png',
                        message: '安排起来，这个做法很简单的哦。',
                        dateTime: '2023-02-28 13:23',
                        location: '广东',
                        favoriteCount: 1,
                        isFavorite: false,
                    },
                ],
            },
            {
                userName: '左半',
                avatarUrl: '/avatar/avatar_39.png',
                message: '看着真有食欲',
                dateTime: '2023-02-28 09:09',
                location: '福建',
                favoriteCount: 2,
                isFavorite: false,
                children: null,
            },
            {
                userName: 'TTTi',
                avatarUrl: '/avatar/avatar_38.png',
                message: '这个比我做的看着就好吃',
                dateTime: '2023-02-28 11:11',
                location: '河南',
                favoriteCount: 3,
                isFavorite: false,
                children: null,
            },
            {
                userName: '衣衣一',
                avatarUrl: '/avatar/avatar_37.png',
                message: '明天我就做这个菜，再做个西兰花',
                dateTime: '2023-02-28 11:34',
                location: '天津',
                favoriteCount: 1,
                isFavorite: false,
                children: null,
            },
            {
                userName: '淡淡的',
                avatarUrl: '/avatar/avatar_36.png',
                message: '好好吃的样子啊',
                dateTime: '2023-02-28 11:35',
                location: '安徽',
                favoriteCount: 0,
                isFavorite: false,
                children: null,
            },
            {
                userName: 'TyTyTy',
                avatarUrl: '/avatar/avatar_36.png',
                message: '这个做起来简单吗，我想学',
                dateTime: '2023-02-28 11:35',
                location: '河南',
                favoriteCount: 1,
                isFavorite: false,
                children: null,
            },
            {
                userName: '马大哈11',
                avatarUrl: '/avatar/avatar_36.png',
                message: '这个好好吃，今晚多吃一碗饭',
                dateTime: '2023-02-28 11:35',
                location: '北京',
                favoriteCount: 1,
                isFavorite: false,
                children: null,
            },
        ],
    },
    // article 3 - 风景摄影日落（来自真实XHS笔记）
    {
        id: 3,
        title: '怀柔水库-日落',
        desc: '傍晚的怀柔水库，日落时分的光线美到窒息。\n每一帧都像油画一样，值得反复回味。',
        tag: ['日落', '风景摄影', '怀柔', '治愈系风景', '手机壁纸'],
        dateTime: '2023-02-28 16:00',
        location: '北京',
        userId: 3,
        userName: '小小风筝',
        isFollow: false,
        avatarUrl: '/avatar/avatar_03.png',
        images: [
            'http://ci.xiaohongshu.com/notes_pre_post/1040g3k031l8disdplm5g5o98lu3g8ngr86suaco?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/notes_pre_post/1040g3k031l8disdplm605o98lu3g8ngric8digg?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/notes_pre_post/1040g3k031l8disdplm6g5o98lu3g8ngrbfa8rj8?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/notes_pre_post/1040g3k031l8dpqfg5o005o98lu3g8ngr896um38?imageView2/2/w/1080/format/jpg',
        ],
        favoriteCount: 18700,
        collectionCount: 2088,
        isFavorite: false,
        isCollection: false,
        comments: [
            {
                userName: 'ABC',
                avatarUrl: '/avatar/avatar_35.png',
                message: '忽然想起欧珑的那支香水，柑橘味的加州盛夏',
                dateTime: '2023-02-28 07:23',
                location: '成都',
                favoriteCount: 45,
                isFavorite: false,
                children: [
                    {
                        userName: '小小风筝',
                        avatarUrl: '/avatar/avatar_03.png',
                        message: '我还真的有这个',
                        dateTime: '2023-02-28 13:23',
                        location: '美国',
                        favoriteCount: 1,
                        isFavorite: false,
                    },
                ],
            },
            {
                userName: '仙女',
                avatarUrl: '/avatar/avatar_34.png',
                message: '这也太call me by your name了吧',
                dateTime: '2023-02-28 09:09',
                location: '福建',
                favoriteCount: 2,
                isFavorite: false,
                children: null,
            },
            {
                userName: 'Chery',
                avatarUrl: '/avatar/avatar_33.png',
                message: '微博也关注你了，没想到在小红书也看到你了',
                dateTime: '2023-02-28 11:11',
                location: '河南',
                favoriteCount: 3,
                isFavorite: false,
                children: null,
            },
            {
                userName: '时雨',
                avatarUrl: '/avatar/avatar_32.png',
                message: '本来有糟糕的情绪，看到这个风景一下子舒服了很多',
                dateTime: '2023-02-28 11:34',
                location: '山东',
                favoriteCount: 1,
                isFavorite: false,
                children: null,
            },
            {
                userName: '菠萝',
                avatarUrl: '/avatar/avatar_31.png',
                message: '啊啊啊啊啊啊好美，我宣布它将成为我下个阶段的手机壁纸',
                dateTime: '2023-02-28 11:35',
                location: '上海',
                favoriteCount: 0,
                isFavorite: false,
                children: null,
            },
            {
                userName: '圈圈',
                avatarUrl: '/avatar/avatar_30.png',
                message: '我已经闻到了清新的橘子的气息',
                dateTime: '2023-02-28 11:35',
                location: '河南',
                favoriteCount: 1,
                isFavorite: false,
                children: null,
            },
            {
                userName: 'Biss',
                avatarUrl: '/avatar/avatar_29.png',
                message: '好好看，求原图',
                dateTime: '2023-02-28 11:35',
                location: '北京',
                favoriteCount: 1,
                isFavorite: false,
                children: null,
            },
        ],
    },
    // article 4 - 湖景风景（来自真实XHS笔记）
    {
        id: 4,
        title: '审美积累｜Lee',
        desc: '远处的小船越来越近\n船桨拨动着湖面激起涟漪\n在阳光下波光粼粼\n绘成了我心中的春日画',
        tag: ['审美积累', '治愈风景', '笔记灵感', '摄影', '湖景'],
        dateTime: '2023-03-03 11:00',
        location: '浙江',
        userId: 4,
        userName: '失忆',
        isFollow: false,
        avatarUrl: '/avatar/avatar_04.png',
        images: [
            'http://ci.xiaohongshu.com/notes_pre_post/1040g3k031q2cgaru002048jjnrr56mgkkgr7p6o?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/notes_pre_post/1040g3k031q2cgaru002g48jjnrr56mgkea9mkl8?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/notes_pre_post/1040g3k031q2cgaru001g48jjnrr56mgkdgsqb1g?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/notes_pre_post/1040g3k031q2cgaru005g48jjnrr56mgk6mlui3o?imageView2/2/w/1080/format/jpg',
        ],
        favoriteCount: 8700,
        collectionCount: 288,
        isFavorite: true,
        isCollection: false,
        comments: [
            {
                userName: '纠结',
                avatarUrl: '/avatar/avatar_28.png',
                message: '我保存了图片，我要做手机壁纸',
                dateTime: '2023-02-28 07:23',
                location: '浙江',
                favoriteCount: 45,
                isFavorite: false,
                children: [
                    {
                        userName: '失忆',
                        avatarUrl: '/avatar/avatar_04.png',
                        message: '好的呦',
                        dateTime: '2023-02-28 13:23',
                        location: '浙江',
                        favoriteCount: 1,
                        isFavorite: false,
                    },
                ],
            },
            {
                userName: '貂貂',
                avatarUrl: '/avatar/avatar_27.png',
                message: '这是什么相机拍的，太好看了吧',
                dateTime: '2023-02-28 09:09',
                location: '福建',
                favoriteCount: 2,
                isFavorite: false,
                children: null,
            },
            {
                userName: '风风',
                avatarUrl: '/avatar/avatar_26.png',
                message: '这是西湖吗',
                dateTime: '2023-02-28 11:11',
                location: '河南',
                favoriteCount: 3,
                isFavorite: false,
                children: null,
            },
            {
                userName: '于桑',
                avatarUrl: '/avatar/avatar_25.png',
                message: '哇，这个图我刷到好几次了，是原作吗',
                dateTime: '2023-03-04 11:34',
                location: '山东',
                favoriteCount: 1,
                isFavorite: false,
                children: null,
            },
            {
                userName: '蘑菇',
                avatarUrl: '/avatar/avatar_24.png',
                message: '好漂亮',
                dateTime: '2023-02-28 11:35',
                location: '上海',
                favoriteCount: 0,
                isFavorite: false,
                children: null,
            },
            {
                userName: '煤球',
                avatarUrl: '/avatar/avatar_23.png',
                message: '太好看了吧',
                dateTime: '2023-02-28 11:35',
                location: '河南',
                favoriteCount: 1,
                isFavorite: false,
                children: null,
            },
            {
                userName: '尘埃',
                avatarUrl: '/avatar/avatar_22.png',
                message: '哇，你摄影技术好好啊',
                dateTime: '2023-02-28 11:35',
                location: '北京',
                favoriteCount: 1,
                isFavorite: false,
                children: null,
            },
        ],
    },
    // article 5 - 花摄影（来自真实XHS笔记）
    {
        id: 5,
        title: '国家植物园-山桃花/小溪',
        desc: '三月的国家植物园\n山桃花开了\n小溪边的花瓣随水流走\n像极了一幅流动的画',
        tag: ['花', '摄影', '植物园', '春天', '山桃花'],
        dateTime: '2023-03-03 11:00',
        location: '北京',
        userId: 5,
        userName: '慢慢',
        isFollow: false,
        avatarUrl: '/avatar/avatar_05.png',
        images: [
            'http://ci.xiaohongshu.com/1040g2sg31u3mohchhm005p37i6uqa390d3vpe48?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/notes_pre_post/1040g3k031u4uip1b2u005p37i6uqa390lci2j1o?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/notes_pre_post/1040g3k031u4uip1b2u0g5p37i6uqa390civ64eo?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/notes_pre_post/1040g3k031u4uip1b2u105p37i6uqa390sn2n0gg?imageView2/2/w/1080/format/jpg',
        ],
        favoriteCount: 2655,
        collectionCount: 288,
        isFavorite: false,
        isCollection: false,
        comments: [
            {
                userName: '心事',
                avatarUrl: '/avatar/avatar_22.png',
                message: '我姐姐朋友圈发了相同的图，真的好漂亮，今天又是想家的一天。',
                dateTime: '2023-02-28 07:23',
                location: '江西',
                favoriteCount: 12,
                isFavorite: false,
                children: [
                    {
                        userName: '慢慢',
                        avatarUrl: '/avatar/avatar_05.png',
                        message: '抱抱你',
                        dateTime: '2023-02-28 13:23',
                        location: '成都',
                        favoriteCount: 1,
                        isFavorite: false,
                    },
                ],
            },
            {
                userName: '木木',
                avatarUrl: '/avatar/avatar_21.png',
                message: '这哪里是星星啊，分明是我的梦',
                dateTime: '2023-02-28 09:09',
                location: '福建',
                favoriteCount: 2,
                isFavorite: false,
                children: null,
            },
            {
                userName: '你回来啦',
                avatarUrl: '/avatar/avatar_20.png',
                message: '可不可以出一下教程啊',
                dateTime: '2023-02-28 11:11',
                location: '河南',
                favoriteCount: 3,
                isFavorite: false,
                children: null,
            },
            {
                userName: '起风了',
                avatarUrl: '/avatar/avatar_19.png',
                message: '她的首页还有很多图',
                dateTime: '2023-03-04 11:34',
                location: '山东',
                favoriteCount: 1,
                isFavorite: false,
                children: null,
            },
            {
                userName: '山雾',
                avatarUrl: '/avatar/avatar_18.png',
                message: '这是什么花啊',
                dateTime: '2023-02-28 11:35',
                location: '上海',
                favoriteCount: 0,
                isFavorite: false,
                children: null,
            },
            {
                userName: '馨馨',
                avatarUrl: '/avatar/avatar_17.png',
                message: '怎么想到了水云天',
                dateTime: '2023-02-28 11:35',
                location: '河南',
                favoriteCount: 1,
                isFavorite: false,
                children: null,
            },
            {
                userName: '欢欢',
                avatarUrl: '/avatar/avatar_16.png',
                message: '等梨花开了就去拍照',
                dateTime: '2023-02-28 11:35',
                location: '北京',
                favoriteCount: 1,
                isFavorite: false,
                children: null,
            },
        ],
    },
    // article 6 - 敦煌写真（来自真实XHS笔记）
    {
        id: 6,
        title: '当老公去鸣沙山拍了回头率1000%的敦煌飞天',
        desc: '这次去敦煌\n在鸣沙山拍了飞天造型\n回头率真的超高\n每一张都像从壁画里走出来的仙女',
        tag: ['写真', '敦煌', '飞天', '拍照', '旅行'],
        dateTime: '2023-03-03 11:00',
        location: '甘肃',
        userId: 6,
        userName: '潇潇',
        isFollow: false,
        avatarUrl: '/avatar/avatar_06.png',
        images: [
            'http://ci.xiaohongshu.com/1040g008318ibljn0jq70416g14tfan4tts9rsc8?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/1040g008318ibljn0jq7g416g14tfan4tlj54ajo?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/1040g008318ibljn0jq80416g14tfan4tf298k1g?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/1040g008318ibljn0jq8g416g14tfan4tog1ppd8?imageView2/2/w/1080/format/jpg',
        ],
        favoriteCount: 2655,
        collectionCount: 288,
        isFavorite: false,
        isCollection: false,
        comments: [
            {
                userName: '小猫佳佳',
                avatarUrl: '/avatar/avatar_15.png',
                message: '第一张真的好看啊',
                dateTime: '2023-02-28 07:23',
                location: '江西',
                favoriteCount: 112,
                isFavorite: false,
                children: null,
            },
            {
                userName: '松鹤小登堡',
                avatarUrl: '/avatar/avatar_14.png',
                message: '首图真的太美了，扑面而来的自由气息和青春洋溢',
                dateTime: '2023-02-28 09:09',
                location: '云南',
                favoriteCount: 23,
                isFavorite: false,
                children: null,
            },
            {
                userName: '走走123',
                avatarUrl: '/avatar/avatar_13.png',
                message: '你好，我可以拿这个图片做头像吗？',
                dateTime: '2023-02-28 11:11',
                location: '河南',
                favoriteCount: 3,
                isFavorite: false,
                children: null,
            },
            {
                userName: '想看你a',
                avatarUrl: '/avatar/avatar_12.png',
                message: '万物自由生长，青春在旷野里窸窣作响。',
                dateTime: '2023-03-04 11:34',
                location: '云南',
                favoriteCount: 5,
                isFavorite: false,
                children: null,
            },
            {
                userName: '田字格',
                avatarUrl: '/avatar/avatar_11.png',
                message: '特别喜欢看宫崎骏的动画，喜欢里面的女孩子，身材比例和你一样，一度以为这只是动画人物，看到首图终于明白艺术源于生活。',
                dateTime: '2023-02-28 11:35',
                location: '山东',
                favoriteCount: 1112,
                isFavorite: false,
                children: null,
            },
            {
                userName: 'wasdbbb',
                avatarUrl: '/avatar/avatar_10.png',
                message: '第一眼还以为是宫崎骏的动画呢',
                dateTime: '2023-02-28 11:35',
                location: '河南',
                favoriteCount: 1,
                isFavorite: false,
                children: null,
            },
            {
                userName: '将秋叶',
                avatarUrl: '/avatar/avatar_09.png',
                message: '首图太美了吧，我要拿来当头像',
                dateTime: '2023-02-28 11:35',
                location: '北京',
                favoriteCount: 1,
                isFavorite: false,
                children: null,
            },
        ],
    },
    // article 7 - 古诗词（来自真实XHS笔记）
    {
        id: 7,
        title: '你读过最惊为天人的诗句是什么？',
        desc: '小舟从此逝，江海寄余生。\n幸得识君桃花面，从此阡陌多暖春。\n行到水穷处，坐看云起时。\n花开花落终有时，相逢相聚本无意。\n静待一树花开，盼你叶落归来。',
        tag: ['古诗词', '惊艳', '笔记', '灵感', '文学'],
        dateTime: '2023-03-04 12:00',
        location: '山东',
        userId: 7,
        userName: '青鸳',
        isFollow: false,
        avatarUrl: '/avatar/avatar_07.png',
        images: [
            'http://ci.xiaohongshu.com/1040g2sg317ilq5qp0mdg5pmhig4nc9g6vc72250?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/1040g2sg317ilq5qp0md05pmhig4nc9g6tr1529g?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/1040g2sg317ilq5qp0mcg5pmhig4nc9g65kdbnb8?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/1040g2sg317ilq5qp0mc05pmhig4nc9g63kld43g?imageView2/2/w/1080/format/jpg',
        ],
        favoriteCount: 1998,
        collectionCount: 233,
        isFavorite: false,
        isCollection: false,
        comments: [],
    },
    // article 8 - 高分电影（来自真实XHS笔记）
    {
        id: 8,
        title: '快交出你们近期的高分电影清单！',
        desc: '分享各领域的干货\n人海茫茫，有缘遇到，那就点赞关注收藏吧\n我们一起加油变得更加优秀',
        tag: ['高分电影', '电影推荐', '影单', '周末看什么'],
        dateTime: '2023-03-04 15:00',
        location: '云南',
        userId: 8,
        userName: '潇潇',
        isFollow: true,
        avatarUrl: '/avatar/avatar_08.png',
        images: [
            'http://ci.xiaohongshu.com/1040g00831r1bft08n46g5n2mtigkab6ocf2dksg?imageView2/2/w/1080/format/jpg',
        ],
        favoriteCount: 2655,
        collectionCount: 288,
        isFavorite: false,
        isCollection: false,
        comments: [
            {
                userName: '江敏',
                avatarUrl: '/avatar/avatar_06.png',
                message: '蓝白红三部曲应该出现在你的片单里',
                dateTime: '2023-02-28 07:23',
                location: '上海',
                favoriteCount: 8,
                isFavorite: false,
                children: null,
            },
            {
                userName: 'Klok',
                avatarUrl: '/avatar/avatar_05.png',
                message: '王家卫、侯孝贤、李安也不错哦',
                dateTime: '2023-02-28 09:09',
                location: '云南',
                favoriteCount: 23,
                isFavorite: false,
                children: null,
            },
            {
                userName: '欢欢',
                avatarUrl: '/avatar/avatar_04.png',
                message: '春夏秋冬又一集',
                dateTime: '2023-02-28 11:11',
                location: '河南',
                favoriteCount: 3,
                isFavorite: false,
                children: null,
            },
            {
                userName: 'wild',
                avatarUrl: '/avatar/avatar_03.png',
                message: '最香民谣真的好好看啊！',
                dateTime: '2023-03-04 11:34',
                location: '云南',
                favoriteCount: 5,
                isFavorite: false,
                children: null,
            },
            {
                userName: 'slide',
                avatarUrl: '/avatar/avatar_02.png',
                message: '你的片单真的好，都是好电影，每一个都值得反复看几遍，支持支持！',
                dateTime: '2023-02-28 11:35',
                location: '山东',
                favoriteCount: 1112,
                isFavorite: false,
                children: null,
            },
            {
                userName: '毛衣',
                avatarUrl: '/avatar/avatar_01.png',
                message: '曾经有一份真挚的爱摆在我面前，而我没有珍惜，等到失去后才后悔莫及。',
                dateTime: '2023-02-28 11:35',
                location: '河南',
                favoriteCount: 1,
                isFavorite: false,
                children: null,
            },
        ],
    },
    // article 9 - 英国田园（来自真实XHS笔记）
    {
        id: 9,
        title: '伦敦1h直达|走进英伦田园油画里',
        desc: '大片的草地\n复古的建筑\n优美的环境\n清新的空气\n伦敦出发一小时就能到达这片世外桃源',
        tag: ['浪漫生活', '英国乡村', '田园风', '田园生活', '乡村小屋', '童话风'],
        dateTime: '2023-03-05 12:12',
        location: '英国',
        userId: 9,
        userName: 'StiffKit',
        isFollow: true,
        avatarUrl: '/avatar/avatar_09.png',
        images: [
            'http://ci.xiaohongshu.com/notes_pre_post/1040g3k031ldc6lu25mbg49uq2qd5j623odr7ue0?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/notes_pre_post/1040g3k031ldc6lu25mc049uq2qd5j6236579dp8?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/notes_pre_post/1040g3k031ldc6lu25mcg49uq2qd5j623k5gppig?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/notes_pre_post/1040g3k031ldc6lu25md049uq2qd5j6230mqsv2g?imageView2/2/w/1080/format/jpg',
        ],
        favoriteCount: 1244,
        collectionCount: 260,
        isFavorite: false,
        isCollection: false,
        comments: [
            {
                userName: 'stack',
                avatarUrl: '/avatar/avatar_40.png',
                message: '梦幻之地',
                dateTime: '2023-02-28 07:23',
                location: '上海',
                favoriteCount: 8,
                isFavorite: false,
                children: null,
            },
            {
                userName: '小霜霜',
                avatarUrl: '/avatar/avatar_39.png',
                message: '人越少的地方，越像童话',
                dateTime: '2023-03-05 13:09',
                location: '云南',
                favoriteCount: 23,
                isFavorite: false,
                children: null,
            },
            {
                userName: '夏威夷的风',
                avatarUrl: '/avatar/avatar_38.png',
                message: '这是我向往的生活',
                dateTime: '2023-03-05 11:11',
                location: '河南',
                favoriteCount: 3,
                isFavorite: false,
                children: null,
            },
            {
                userName: '舒心',
                avatarUrl: '/avatar/avatar_37.png',
                message: '好棒啊',
                dateTime: '2023-03-04 11:34',
                location: '云南',
                favoriteCount: 5,
                isFavorite: false,
                children: null,
            },
            {
                userName: 'JoJo',
                avatarUrl: '/avatar/avatar_36.png',
                message: '太美了这色调！',
                dateTime: '2023-03-05 11:35',
                location: '山东',
                favoriteCount: 1112,
                isFavorite: false,
                children: null,
            },
            {
                userName: '书草',
                avatarUrl: '/avatar/avatar_35.png',
                message: '好喜欢这地方，我想住过去',
                dateTime: '2023-02-28 11:35',
                location: '河南',
                favoriteCount: 1,
                isFavorite: false,
                children: null,
            },
        ],
    },
    // article 10 - 日本插画（来自真实XHS笔记）
    {
        id: 10,
        title: '日本插画师kunomari',
        desc: '日本插画师kunomari的作品\n治愈系的画风\n每一幅都充满温暖和阳光\n让人看了心情特别好',
        tag: ['插画', '手绘', '日本插画师', '治愈系', '艺术'],
        dateTime: '2023-03-05 12:12',
        location: '广东',
        userId: 10,
        userName: '潇潇陌陌',
        isFollow: true,
        avatarUrl: '/avatar/avatar_10.png',
        images: [
            'http://ci.xiaohongshu.com/notes_pre_post/1040g3k831ii8g8u7geb04a5r6e3j25liv5eoqa0?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/notes_pre_post/1040g3k831ii8g8u7gebg4a5r6e3j25lin0nnn30?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/notes_pre_post/1040g3k831ii8g8u7gec04a5r6e3j25li409rovo?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/notes_pre_post/1040g3k831ii8g8u7gecg4a5r6e3j25lij4rmea8?imageView2/2/w/1080/format/jpg',
        ],
        favoriteCount: 3044,
        collectionCount: 1200,
        isFavorite: false,
        isCollection: false,
        comments: [
            {
                userName: '尔尔',
                avatarUrl: '/avatar/avatar_34.png',
                message: '忍不住点赞啊，真的好看',
                dateTime: '2023-02-28 07:23',
                location: '上海',
                favoriteCount: 8,
                isFavorite: false,
                children: null,
            },
            {
                userName: 'yoyo',
                avatarUrl: '/avatar/avatar_33.png',
                message: '现在的插画师越来越牛了',
                dateTime: '2023-03-05 13:09',
                location: '云南',
                favoriteCount: 23,
                isFavorite: false,
                children: null,
            },
            {
                userName: 'super',
                avatarUrl: '/avatar/avatar_32.png',
                message: '烤箱里面放柴火是吧',
                dateTime: '2023-03-05 11:11',
                location: '河南',
                favoriteCount: 3,
                isFavorite: false,
                children: null,
            },
            {
                userName: '小枫',
                avatarUrl: '/avatar/avatar_31.png',
                message: '虽然AI插画很强，但是我还是喜欢人画的，有灵魂在里面',
                dateTime: '2023-03-04 11:34',
                location: '云南',
                favoriteCount: 5,
                isFavorite: false,
                children: null,
            },
            {
                userName: '小怪兽',
                avatarUrl: '/avatar/avatar_30.png',
                message: '哈哈好喜欢这个地方啊',
                dateTime: '2023-03-05 11:35',
                location: '山东',
                favoriteCount: 1112,
                isFavorite: false,
                children: null,
            },
            {
                userName: '蓝莓',
                avatarUrl: '/avatar/avatar_29.png',
                message: '这样的环境是给仙女制造的',
                dateTime: '2023-02-28 11:35',
                location: '河南',
                favoriteCount: 1,
                isFavorite: false,
                children: null,
            },
        ],
    },
    // article 11 - 可爱头像壁纸（来自真实XHS笔记）
    {
        id: 11,
        title: '天吶！被風中凌亂的小狗治愈了！',
        desc: '风中凌乱的小狗也太可爱了吧！！',
        tag: ['可爱', '壁纸', '头像', '小狗', '治愈'],
        dateTime: '2023-03-05 12:12',
        location: '云南',
        userId: 11,
        userName: '觉觉子',
        isFollow: true,
        avatarUrl: '/avatar/avatar_11.png',
        images: [
            'http://ci.xiaohongshu.com/spectrum/1040g34o31grp0imkj43g4105hafoabbk173l4d8?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/spectrum/1040g0k031grp0ihs3c3g4105hafoabbkrqmkjs0?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/spectrum/1040g0k031grp0ihs3c5g4105hafoabbk1qoq3p0?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/spectrum/1040g34o31grp0imkj4204105hafoabbkdr4st18?imageView2/2/w/1080/format/jpg',
        ],
        favoriteCount: 1050,
        collectionCount: 28,
        isFavorite: true,
        isCollection: false,
        comments: [
            {
                userName: '倪妮',
                avatarUrl: '/avatar/avatar_28.png',
                message: '这个博主太可爱了吧，关注了',
                dateTime: '2023-02-28 07:23',
                location: '上海',
                favoriteCount: 8,
                isFavorite: false,
                children: null,
            },
            {
                userName: '夏天',
                avatarUrl: '/avatar/avatar_27.png',
                message: '可以做头像吗，心情好好',
                dateTime: '2023-03-05 13:09',
                location: '云南',
                favoriteCount: 23,
                isFavorite: false,
                children: null,
            },
            {
                userName: '叮当',
                avatarUrl: '/avatar/avatar_26.png',
                message: '哇哦，我以为是宫崎骏的动画片',
                dateTime: '2023-03-05 11:11',
                location: '河南',
                favoriteCount: 3,
                isFavorite: false,
                children: null,
            },
            {
                userName: '某某',
                avatarUrl: '/avatar/avatar_25.png',
                message: '喜欢',
                dateTime: '2023-03-04 11:34',
                location: '云南',
                favoriteCount: 5,
                isFavorite: false,
                children: null,
            },
            {
                userName: '美美',
                avatarUrl: '/avatar/avatar_24.png',
                message: 'ai画的吧，好美啊',
                dateTime: '2023-03-05 11:35',
                location: '山东',
                favoriteCount: 1112,
                isFavorite: false,
                children: null,
            },
        ],
    },
    // article 12 - 穿搭日常（来自真实XHS笔记）
    {
        id: 12,
        title: '早春就让男朋友这样穿，少年感满满',
        desc: '早春穿搭分享\n干净清爽的少年感\n简单搭配就很好看',
        tag: ['穿搭', 'OOTD', '早春穿搭', '少年感', '男友穿搭'],
        dateTime: '2023-03-05 12:12',
        location: '北京',
        userId: 12,
        userName: '秋秋',
        isFollow: true,
        avatarUrl: '/avatar/avatar_12.png',
        images: [
            'http://ci.xiaohongshu.com/1040g2sg31rsmpd042ge05pm802unc8gct4vv688?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/1040g2sg31rsmpd042geg5pm802unc8gcin0ekj8?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/1040g2sg31rsmpd042gf05pm802unc8gcugit0rg?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/1040g2sg31rsmpd042gfg5pm802unc8gcdtj5kbg?imageView2/2/w/1080/format/jpg',
        ],
        favoriteCount: 2010,
        collectionCount: 198,
        isFavorite: true,
        isCollection: false,
        comments: [
            {
                userName: 'yox',
                avatarUrl: '/avatar/avatar_23.png',
                message: '你知道女高中生的诱惑有多大吗',
                dateTime: '2023-02-28 07:23',
                location: '上海',
                favoriteCount: 8,
                isFavorite: false,
                children: null,
            },
            {
                userName: '上善若水',
                avatarUrl: '/avatar/avatar_22.png',
                message: '妈呀，好好看',
                dateTime: '2023-03-05 13:09',
                location: '云南',
                favoriteCount: 23,
                isFavorite: false,
                children: null,
            },
            {
                userName: 'Kuli',
                avatarUrl: '/avatar/avatar_21.png',
                message: '小姐姐好好看啊',
                dateTime: '2023-03-05 11:11',
                location: '河南',
                favoriteCount: 3,
                isFavorite: false,
                children: null,
            },
            {
                userName: '水波1kk',
                avatarUrl: '/avatar/avatar_20.png',
                message: '同高中生路过',
                dateTime: '2023-03-04 11:34',
                location: '云南',
                favoriteCount: 5,
                isFavorite: false,
                children: null,
            },
            {
                userName: '小野',
                avatarUrl: '/avatar/avatar_19.png',
                message: '高一纯情小奶狗路过',
                dateTime: '2023-03-05 11:35',
                location: '山东',
                favoriteCount: 1112,
                isFavorite: false,
                children: null,
            },
            {
                userName: '红薯',
                avatarUrl: '/avatar/avatar_18.png',
                message: '求联系方式',
                dateTime: '2023-02-28 11:35',
                location: '河南',
                favoriteCount: 1,
                isFavorite: false,
                children: null,
            },
        ],
    },
    // article 13 - 旅行拍照（来自真实XHS笔记）
    {
        id: 13,
        title: '地标建筑实用拍照技巧 拒绝背景人多杂乱',
        desc: '旅行拍照不用愁\n掌握这几个技巧\n再多人也能拍出大片感',
        tag: ['拍照技巧', '旅行', '摄影教程', '地标建筑'],
        dateTime: '2023-03-05 12:12',
        location: '广东',
        userId: 13,
        userName: 'PPUit',
        isFollow: true,
        avatarUrl: '/avatar/avatar_13.png',
        images: [
            'http://ci.xiaohongshu.com/1040g008319o6fh1l7a005n34rou4l6mu760p6g8?imageView2/2/w/1080/format/jpg',
        ],
        favoriteCount: 2010,
        collectionCount: 198,
        isFavorite: true,
        isCollection: false,
        comments: [
            {
                userName: '尔尔',
                avatarUrl: '/avatar/avatar_34.png',
                message: '忍不住点赞啊，真的好看',
                dateTime: '2023-02-28 07:23',
                location: '上海',
                favoriteCount: 8,
                isFavorite: false,
                children: null,
            },
            {
                userName: 'yoyo',
                avatarUrl: '/avatar/avatar_33.png',
                message: '现在的插画师越来越牛了',
                dateTime: '2023-03-05 13:09',
                location: '云南',
                favoriteCount: 23,
                isFavorite: false,
                children: null,
            },
            {
                userName: 'super',
                avatarUrl: '/avatar/avatar_32.png',
                message: '烤箱里面放柴火是吧',
                dateTime: '2023-03-05 11:11',
                location: '河南',
                favoriteCount: 3,
                isFavorite: false,
                children: null,
            },
            {
                userName: '小枫',
                avatarUrl: '/avatar/avatar_31.png',
                message: '虽然AI插画很强，但是我还是喜欢人画的，有灵魂在里面',
                dateTime: '2023-03-04 11:34',
                location: '云南',
                favoriteCount: 5,
                isFavorite: false,
                children: null,
            },
            {
                userName: '小怪兽',
                avatarUrl: '/avatar/avatar_30.png',
                message: '哈哈好喜欢这个地方啊',
                dateTime: '2023-03-05 11:35',
                location: '山东',
                favoriteCount: 1112,
                isFavorite: false,
                children: null,
            },
            {
                userName: '蓝莓',
                avatarUrl: '/avatar/avatar_29.png',
                message: '这样的环境是给仙女制造的',
                dateTime: '2023-02-28 11:35',
                location: '河南',
                favoriteCount: 1,
                isFavorite: false,
                children: null,
            },
        ],
    },
    // article 14 - 自我提升（来自真实XHS笔记）
    {
        id: 14,
        title: '去做这9件事拉开你与同龄人的差距',
        desc: '不愧是央视推荐，每一个都是经典\n坚持这9件事，你会越来越优秀',
        tag: ['自我提升', '成长', '努力', '个人成长', '好习惯'],
        dateTime: '2023-03-05 12:12',
        location: '广东',
        userId: 14,
        userName: '创业笔记',
        isFollow: true,
        avatarUrl: '/avatar/avatar_14.png',
        images: [
            'http://ci.xiaohongshu.com/1040g00831aj82d8mnc5g5pj4dtbgu32227hnh60?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/1040g00831aj82d8mnc6g5pj4dtbgu322esq1p38?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/1040g00831aj82d8mnc505pj4dtbgu322ggldcfg?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/1040g00831aj82d8mnc4g5pj4dtbgu322lo9666g?imageView2/2/w/1080/format/jpg',
        ],
        favoriteCount: 2010,
        collectionCount: 198,
        isFavorite: false,
        isCollection: false,
        comments: [
            {
                userName: '华哥',
                avatarUrl: '/avatar/avatar_17.png',
                message: '毒鸡汤，下班了还不让人休息娱乐一下',
                dateTime: '2023-02-28 07:23',
                location: '上海',
                favoriteCount: 8,
                isFavorite: false,
                children: [
                    {
                        userName: '逆风',
                        avatarUrl: '/avatar/avatar_16.png',
                        message: '就是就是',
                        dateTime: '2023-02-28 08:23',
                        location: '上海',
                        favoriteCount: 1,
                        isFavorite: false,
                        children: null,
                    }
                ],
            },
            {
                userName: 'Xing',
                avatarUrl: '/avatar/avatar_15.png',
                message: '上班就已经够卷了，下班还要卷。',
                dateTime: '2023-02-28 07:23',
                location: '河南',
                favoriteCount: 8,
                isFavorite: false,
                children: null,
            },
        ],
    },
    // article 15 - 柯基宠物（来自真实XHS笔记）
    {
        id: 15,
        title: '柯基和边牧的串串应该叫什么',
        desc: '柯基和边牧的串串\n到底应该叫柯牧还是边基呢？\n不管叫什么，都太可爱了吧！',
        tag: ['柯基', '宠物', '狗狗', '萌宠', '可爱'],
        dateTime: '2023-03-05 12:12',
        location: '内蒙古',
        userId: 15,
        userName: '小小画童',
        isFollow: true,
        avatarUrl: '/avatar/avatar_15.png',
        images: [
            'http://ci.xiaohongshu.com/notes_pre_post/1040g3k031opc169ml2005oimm1p41i6jguce0jo?imageView2/2/w/1080/format/jpg',
        ],
        favoriteCount: 340,
        collectionCount: 66,
        isFavorite: false,
        isCollection: false,
        comments: [
            {
                userName: 'CCHHOO',
                avatarUrl: '/avatar/avatar_14.png',
                message: '我可以拿来当头像吗',
                dateTime: '2023-02-28 07:23',
                location: '广东',
                favoriteCount: 8,
                isFavorite: false,
                children: [
                    {
                        userName: '小小画童',
                        avatarUrl: '/avatar/avatar_15.png',
                        message: '当然可以啊',
                        dateTime: '2023-02-28 07:23',
                        location: '内蒙古',
                        favoriteCount: 1,
                        isFavorite: false,
                        children: null,
                    }
                ],
            },
            {
                userName: '火锅',
                avatarUrl: '/avatar/avatar_13.png',
                message: '王牌飞行员申请出战',
                dateTime: '2023-03-05 13:09',
                location: '云南',
                favoriteCount: 23,
                isFavorite: false,
                children: null,
            },
            {
                userName: '柴瘥',
                avatarUrl: '/avatar/avatar_12.png',
                message: '太可爱了吧',
                dateTime: '2023-03-05 11:11',
                location: '河南',
                favoriteCount: 3,
                isFavorite: false,
                children: null,
            },
            {
                userName: '甜甜',
                avatarUrl: '/avatar/avatar_13.png',
                message: '可爱，想要看雪纳瑞飞行员',
                dateTime: '2023-03-04 11:34',
                location: '云南',
                favoriteCount: 5,
                isFavorite: false,
                children: null,
            },
            {
                userName: 'CoCo',
                avatarUrl: '/avatar/avatar_12.png',
                message: '喜欢，点赞点赞',
                dateTime: '2023-03-05 11:35',
                location: '山东',
                favoriteCount: 1112,
                isFavorite: false,
                children: null,
            },
        ],
    },
    // article 16 - Pitt 急诊室美剧（来自真实XHS笔记）
    {
        id: 16,
        title: 'Apple TV 口碑爆棚【硬核医疗剧】Pitt',
        desc: '2025年Apple TV+新剧《Pitt》\nNoah Wyle主演，讲述匹兹堡一家医院急诊室的故事\n节奏紧凑，每集一个班次，真实还原急诊室的混乱与温情\n看过《急诊室的故事》的观众一定不能错过！',
        tag: ['美剧', 'AppleTV', 'Pitt', '医疗剧', '急诊室', 'NoahWyle'],
        dateTime: '2025-06-29 12:48',
        location: '上海',
        userId: 3,
        userName: '美剧研究所',
        isFollow: false,
        avatarUrl: '/avatar/avatar_16.png',
        images: [
            'http://ci.xiaohongshu.com/spectrum/1040g34o31qrgvfa072105p9nr2eh162us78d680?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/spectrum/1040g0k031qrgvq6in2005p9nr2eh162uu3seohg?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/spectrum/1040g34o31qrgvmfp6u605p9nr2eh162ur8f5t48?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/spectrum/1040g34o31qrgvmfp6u6g5p9nr2eh162u5ptbhc8?imageView2/2/w/1080/format/jpg',
        ],
        favoriteCount: 7913,
        collectionCount: 5621,
        isFavorite: true,
        isCollection: true,
        comments: [
            {
                userName: '追光少年',
                avatarUrl: '/avatar/avatar_25.png',
                message: 'Noah Wyle回归医疗剧了！太激动了！',
                dateTime: '2025-06-30 08:20',
                location: '北京',
                favoriteCount: 89,
                isFavorite: false,
                children: [
                    {
                        userName: '小飞飞',
                        avatarUrl: '/avatar/avatar_40.png',
                        message: '急诊室的故事yyds',
                        dateTime: '2025-06-30 09:10',
                        location: '广东',
                        favoriteCount: 12,
                        isFavorite: false,
                    },
                ],
            },
            {
                userName: '周末电影院',
                avatarUrl: '/avatar/avatar_26.png',
                message: '每集一个班次的设计太聪明了，节奏感拉满',
                dateTime: '2025-06-30 10:15',
                location: '杭州',
                favoriteCount: 45,
                isFavorite: false,
                children: null,
            },
            {
                userName: '影迷小马',
                avatarUrl: '/avatar/avatar_27.png',
                message: '终于有一部正经的硬核医疗剧了，不是恋爱剧挂医疗的皮',
                dateTime: '2025-06-30 11:30',
                location: '深圳',
                favoriteCount: 67,
                isFavorite: false,
                children: null,
            },
            {
                userName: '电影研究所',
                avatarUrl: '/avatar/avatar_28.png',
                message: '匹兹堡取景太真实了，急诊室的紧张感扑面而来',
                dateTime: '2025-07-01 09:00',
                location: '成都',
                favoriteCount: 34,
                isFavorite: false,
                children: null,
            },
            {
                userName: '光影日记',
                avatarUrl: '/avatar/avatar_29.png',
                message: '看了三集了，质量非常高，推荐给所有喜欢医疗剧的朋友',
                dateTime: '2025-07-01 14:20',
                location: '南京',
                favoriteCount: 23,
                isFavorite: false,
                children: null,
            },
        ],
    },
    // article 17 - 京都旅行攻略（来自真实XHS笔记）
    {
        id: 17,
        title: '对自己的京都4天3晚攻略满意到睡不着',
        desc: '每次去关西都会去京都，这座古都值得多住几晚\n📍【行程】\nD1: 落地大阪关西机场 -> 京都站 -> 办理入住\nD2: 清水寺 -> 伏见稻荷大社\nD3: 岚山\nD4: 三千院 -> 琉璃光院',
        tag: ['日本旅行', '日本旅游攻略', '京都', '京都旅行', '京都美食', '旅游攻略'],
        dateTime: '2025-07-19 20:14',
        location: '京都',
        userId: 4,
        userName: '旅行的蜗牛',
        isFollow: true,
        avatarUrl: '/avatar/avatar_17.png',
        images: [
            'http://ci.xiaohongshu.com/1040g00831k4apcumj20049lja1kn2n406pit1io?imageView2/2/w/1080/format/jpg',
        ],
        favoriteCount: 19578,
        collectionCount: 12800,
        isFavorite: true,
        isCollection: true,
        comments: [
            {
                userName: '小红薯旅行家',
                avatarUrl: '/avatar/avatar_27.png',
                message: '不会日语适合去吗',
                dateTime: '2025-07-20 09:30',
                location: '广州',
                favoriteCount: 32,
                isFavorite: false,
                children: [
                    {
                        userName: '旅行的蜗牛',
                        avatarUrl: '/avatar/avatar_17.png',
                        message: '不用会日语也可以来，勇敢的人先享受世界',
                        dateTime: '2025-07-20 10:00',
                        location: '京都',
                        favoriteCount: 15,
                        isFavorite: false,
                    },
                ],
            },
            {
                userName: '鸭川散步',
                avatarUrl: '/avatar/avatar_30.png',
                message: '18年在京都住了三个月，那时候觉得是环游世界的开始，没想到却是结束。',
                dateTime: '2025-07-20 11:15',
                location: '上海',
                favoriteCount: 156,
                isFavorite: false,
                children: null,
            },
            {
                userName: '穷游小能手',
                avatarUrl: '/avatar/avatar_31.png',
                message: '酒店好贵啊，6-8千一晚',
                dateTime: '2025-07-20 14:00',
                location: '北京',
                favoriteCount: 78,
                isFavorite: false,
                children: [
                    {
                        userName: '樱花季',
                        avatarUrl: '/avatar/avatar_32.png',
                        message: '你开玩笑吧，正常五百～一千之内',
                        dateTime: '2025-07-20 15:30',
                        location: '大阪',
                        favoriteCount: 45,
                        isFavorite: false,
                    },
                ],
            },
            {
                userName: '岚山小火车',
                avatarUrl: '/avatar/avatar_33.png',
                message: '如果只去2天 推荐岚山还是三千院呢',
                dateTime: '2025-07-21 08:00',
                location: '杭州',
                favoriteCount: 23,
                isFavorite: false,
                children: null,
            },
            {
                userName: '攻略收藏家',
                avatarUrl: '/avatar/avatar_34.png',
                message: '太实用了，谢谢，这路线是我喜欢的，准备抄作业啦',
                dateTime: '2025-07-21 10:30',
                location: '深圳',
                favoriteCount: 12,
                isFavorite: false,
                children: null,
            },
        ],
    },
    // article 18 - 美剧推荐（来自真实XHS笔记）
    {
        id: 18,
        title: '15部最受欢迎美英剧｜一天看一季',
        desc: '史上最受欢迎的美剧榜单！每一部都是YYDS!剧荒的快看，不会踩雷哦～\n1️⃣《绝命毒师》2️⃣《老友记》\n3️⃣《无耻之徒》4️⃣《破产姐妹》\n5️⃣《生活大爆炸》6️⃣《越狱》\n7️⃣《怪奇物语》8️⃣《纸牌屋》\n9️⃣《唐顿庄园》🔟《致命女人》',
        tag: ['追剧打卡', '美剧', '经典美剧', '剧荒推荐', '追剧', '英剧', '看美剧学英语'],
        dateTime: '2024-08-18 23:05',
        location: '北京',
        userId: 2,
        userName: '追剧小能手',
        isFollow: false,
        avatarUrl: '/avatar/avatar_18.png',
        images: [
            'http://ci.xiaohongshu.com/1040g008317052iiego605pbq9r773dlgd5scom0?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/1040g008317052iiego5g5pbq9r773dlgnp40uco?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/1040g008317052iiego505pbq9r773dlg3lmbn9g?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/1040g008317052iiego405pbq9r773dlg72vfvvg?imageView2/2/w/1080/format/jpg',
        ],
        favoriteCount: 87114,
        collectionCount: 18900,
        isFavorite: true,
        isCollection: true,
        comments: [
            {
                userName: '夜猫子联盟',
                avatarUrl: '/avatar/avatar_28.png',
                message: '怎么没有摩登家庭啊？',
                dateTime: '2024-08-19 01:30',
                location: '深圳',
                favoriteCount: 156,
                isFavorite: false,
                children: [
                    {
                        userName: '剧迷小马',
                        avatarUrl: '/avatar/avatar_35.png',
                        message: '摩登家庭必须有名字',
                        dateTime: '2024-08-19 08:00',
                        location: '广州',
                        favoriteCount: 34,
                        isFavorite: false,
                    },
                ],
            },
            {
                userName: '周末沙发薯',
                avatarUrl: '/avatar/avatar_29.png',
                message: '唐顿庄园和神探夏洛克都是英剧吧',
                dateTime: '2024-08-19 09:45',
                location: '成都',
                favoriteCount: 78,
                isFavorite: false,
                children: null,
            },
            {
                userName: '布洛芬选手',
                avatarUrl: '/avatar/avatar_36.png',
                message: '强烈推荐《我们这一天》，电子布洛芬！！！',
                dateTime: '2024-08-19 12:00',
                location: '上海',
                favoriteCount: 234,
                isFavorite: false,
                children: null,
            },
            {
                userName: '老友记铁粉',
                avatarUrl: '/avatar/avatar_37.png',
                message: '老友记简直不要太爱！！！！',
                dateTime: '2024-08-19 15:30',
                location: '杭州',
                favoriteCount: 189,
                isFavorite: false,
                children: null,
            },
            {
                userName: '绝命毒师粉',
                avatarUrl: '/avatar/avatar_38.png',
                message: '权游、老友记、绝命毒师，这个顺序还差不多',
                dateTime: '2024-08-20 10:00',
                location: '南京',
                favoriteCount: 67,
                isFavorite: false,
                children: null,
            },
        ],
    },
    // article 19 - 上海咖啡探店（来自真实XHS笔记）
    {
        id: 19,
        title: '每个来沪朋友都会被我带来这里...',
        desc: '1️⃣华山路263\n2️⃣HIFI ACOUSTIC\n3️⃣FLAIR\n4️⃣人民咖啡馆\n5️⃣苏州河畔 汭\n6️⃣天水恋\n7️⃣沙美大楼 the upper room\n8️⃣外滩8号\n9️⃣wabi cafe',
        tag: ['上海citywalk', 'iPhone拍照', '上海探店', '城市探索家', '上海周末去哪儿', '上海旅游'],
        dateTime: '2025-03-06 16:53',
        location: '上海',
        userId: 1,
        userName: '咖啡地图Mia',
        isFollow: true,
        avatarUrl: '/avatar/avatar_19.png',
        images: [
            'http://ci.xiaohongshu.com/1040g00831t9r6b93lk0049vkrkco1uh1pamfhhg?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/1040g00831t9r6b93lk0g49vkrkco1uh1ndspuao?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/1040g00831t9r6b93lk1049vkrkco1uh1v2v8j4g?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/1040g00831t9r6b93lk1g49vkrkco1uh16jt74mo?imageView2/2/w/1080/format/jpg',
        ],
        favoriteCount: 23948,
        collectionCount: 7654,
        isFavorite: false,
        isCollection: true,
        comments: [
            {
                userName: '拿铁不加糖',
                avatarUrl: '/avatar/avatar_30.png',
                message: '土著居民表示一个都没去过',
                dateTime: '2025-03-07 08:00',
                location: '上海',
                favoriteCount: 23,
                isFavorite: false,
                children: null,
            },
            {
                userName: '周末探店王',
                avatarUrl: '/avatar/avatar_31.png',
                message: '人民咖啡馆关门了',
                dateTime: '2025-03-07 10:30',
                location: '上海',
                favoriteCount: 67,
                isFavorite: false,
                children: null,
            },
            {
                userName: '咖啡成瘾',
                avatarUrl: '/avatar/avatar_32.png',
                message: '每张都拍的好好',
                dateTime: '2025-03-07 14:00',
                location: '杭州',
                favoriteCount: 34,
                isFavorite: false,
                children: null,
            },
            {
                userName: '上海小马达',
                avatarUrl: '/avatar/avatar_33.png',
                message: '你好这些地点都集中在一个地方吗，我打算初二去待一星期',
                dateTime: '2025-03-08 09:15',
                location: '成都',
                favoriteCount: 12,
                isFavorite: false,
                children: null,
            },
        ],
    },
    // article 20 - 韩剧推荐（来自真实XHS笔记）
    {
        id: 20,
        title: '高分经典韩剧TOP天花板推荐！！！',
        desc: '高分经典韩剧TOP天花板推荐！经典值得n刷，中国人不骗中国人！\n1⃣️请回答1988 - 青春、怀旧、亲情、催泪预警！\n2⃣️大力女子都奉顺 - 搞笑喜剧、超甜\n3⃣️窥探 - 悬疑、19禁\n4⃣️鬼怪 - 浪漫、爱情、奇幻\n5⃣️顶楼 - 全员疯批！\n6⃣️W两个世界 - 奇幻、爱情\n7⃣️继承者们 - 青春、喜剧\n8⃣️太阳的后裔 - 战争、爱情',
        tag: ['韩剧', '韩剧推荐', '鬼怪', '顶楼', '高甜韩剧', '请回答1988'],
        dateTime: '2024-11-03 12:26',
        location: '杭州',
        userId: 3,
        userName: '韩剧研究所',
        isFollow: false,
        avatarUrl: '/avatar/avatar_20.png',
        images: [
            'http://ci.xiaohongshu.com/1040g2sg31bq6auso0m705n8q7h94m2ltlkc3cso?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/1040g2sg31bq6auso0m7g5n8q7h94m2ltaj7532g?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/1040g2sg31bq6auso0m805n8q7h94m2ltm0217v0?imageView2/2/w/1080/format/jpg',
            'http://ci.xiaohongshu.com/1040g2sg31bq6auso0m8g5n8q7h94m2ltlh4899g?imageView2/2/w/1080/format/jpg',
        ],
        favoriteCount: 16520,
        collectionCount: 9870,
        isFavorite: true,
        isCollection: true,
        comments: [
            {
                userName: '棉花糖少女',
                avatarUrl: '/avatar/avatar_31.png',
                message: '举重妖精金福珠 y y d s',
                dateTime: '2024-11-04 20:30',
                location: '南京',
                favoriteCount: 67,
                isFavorite: false,
                children: [
                    {
                        userName: '海岸村',
                        avatarUrl: '/avatar/avatar_39.png',
                        message: '真的自然不做作，有没有类似的推荐',
                        dateTime: '2024-11-04 21:00',
                        location: '厦门',
                        favoriteCount: 12,
                        isFavorite: false,
                    },
                ],
            },
            {
                userName: '追剧小能手',
                avatarUrl: '/avatar/avatar_18.png',
                message: '鬼怪yyds，还有一部走进我心里的是恋爱的发现',
                dateTime: '2024-11-04 22:00',
                location: '北京',
                favoriteCount: 34,
                isFavorite: false,
                children: null,
            },
            {
                userName: '蓝海传说粉',
                avatarUrl: '/avatar/avatar_34.png',
                message: '蓝色大海的传说居然没有？真的绝好看!!!',
                dateTime: '2024-11-05 09:30',
                location: '上海',
                favoriteCount: 89,
                isFavorite: false,
                children: null,
            },
            {
                userName: '继承者铁粉',
                avatarUrl: '/avatar/avatar_35.png',
                message: '继承者们yyds，三刷完了家人们',
                dateTime: '2024-11-05 14:00',
                location: '广州',
                favoriteCount: 56,
                isFavorite: false,
                children: null,
            },
            {
                userName: '来自星星',
                avatarUrl: '/avatar/avatar_36.png',
                message: '没有人说来自星星的你吗',
                dateTime: '2024-11-06 10:00',
                location: '成都',
                favoriteCount: 45,
                isFavorite: false,
                children: null,
            },
        ],
    },
];

const MOCK_GOODS = [
    {
        id: 1,
        title: '纯小麦粉面粉无小麦麸质低脂杂粮糖友敏宝牛油果果桥本·700g*3袋装',
        image: '/goods/goods01/img_01.jpg',
        price: 51,
        originPrice: null,
        promotion: null,
    },
    {
        id: 2,
        title: '糙米米粉江西米线南仓拌粉螺狮粉800g粗粮无小麦麸',
        image: '/goods/goods02/img_01.jpg',
        price: 84,
        originPrice: null,
        promotion: null,
    },
    {
        id: 3,
        title: '手作一鸣禅意大合集9.9r全新款绕指柔串12mm圆珠抹茶芝士大合集',
        image: '/goods/goods03/img_01.jpg',
        price: 9.9,
        originPrice: 12.8,
        promotion: null,
    },
    {
        id: 4,
        title: '山核桃手串文玩核桃手串手持珠串小核桃串手挂可爆浆深山采核桃',
        image: '/goods/goods04/img_01.jpg',
        price: 9.9,
        originPrice: null,
        promotion: null,
    },
    {
        id: 5,
        title: '纯色素珠5.6R拼手速·纯绿11*12mm',
        image: '/goods/goods05/img_01.jpg',
        price: 5.8,
        originPrice: null,
        promotion: null,
    },
    {
        id: 6,
        title: '天然绿檀木佛珠手串老料和田玉檀香木链男女民族饰品手串',
        image: '/goods/goods06/img_01.jpg',
        price: 12,
        originPrice: null,
        promotion: null,
    },
    {
        id: 7,
        title: '黄油椰子素酥咸蛋黄酥脆饼干椰蓉酥糕点零食酥到没朋友咖啡椰子酥',
        image: '/goods/goods07/img_01.jpg',
        price: 15.8,
        originPrice: null,
        promotion: '满100减18',
    },
    {
        id: 8,
        title: '厚切吐司面包奶香味提拉米苏味手撕面包14袋整箱装混合口味',
        image: '/goods/goods08/img_01.jpg',
        price: 19.9,
        originPrice: 25.98,
        promotion: null,
    },
    {
        id: 9,
        title: '圆包洋车前子壳粉膳食纤维烘焙生酮无小麦麸质0脂250g*2袋装',
        image: '/goods/goods09/img_01.jpg',
        price: 76,
        originPrice: null,
        promotion: '满240减50',
    },
    {
        id: 10,
        title: '广西荔浦水果马蹄荸荠当季零食蔬菜保证新鲜批发价包邮5近王中王',
        image: '/goods/goods10/img_01.jpg',
        price: 75,
        originPrice: null,
        promotion: null,
    },
    {
        id: 11,
        title: '夏天水洗全棉纯色日系棒球帽男女黑色韩版软定鸭舌帽军绿色可调节',
        image: '/goods/goods11/img_01.jpg',
        price: 14,
        originPrice: 18.8,
        promotion: null,
    },
    {
        id: 12,
        title: '纯肉桂粉65g桂皮天然调料冲饮烘焙健身拿铁黄金奶茶桥本65g*2瓶',
        image: '/goods/goods12/img_01.jpg',
        price: 29,
        originPrice: null,
        promotion: null,
    },
    {
        id: 13,
        title: '樱花虾米饼非油炸谷物米饼脆香辣味',
        image: '/goods/goods13/img_01.jpg',
        price: 11.8,
        originPrice: null,
        promotion: null,
    },
    {
        id: 14,
        title: '芒果奶糕草莓干之恋牛扎奶芙芒果干芒果控推荐',
        image: '/goods/goods14/img_01.jpg',
        price: 38.6,
        originPrice: null,
        promotion: null,
    },
    {
        id: 15,
        title: '精品葫芦·直播间选购',
        image: '/goods/goods15/img_01.jpg',
        price: 9.9,
        originPrice: null,
        promotion: null,
    },
    {
        id: 16,
        title: '天然菩提手串三顶菩提根文玩女佛珠手串奶芒12*11mm',
        image: '/goods/goods16/img_01.jpg',
        price: 19.9,
        originPrice: null,
        promotion: null,
    },
    {
        id: 17,
        title: '老北京驴打滚糯米糍粑打年糕东北特产豆面卷休闲小吃即食零食450g',
        image: '/goods/goods17/img_01.jpg',
        price: 14.9,
        originPrice: 19.9,
        promotion: null,
    },
    {
        id: 18,
        title: '奥德斯可可脂原味黑巧克力杏仁夹心巧克力纯手工烘焙网红休闲零食原味方形',
        image: '/goods/goods18/img_01.jpg',
        price: 10.8,
        originPrice: 12.98,
        promotion: null,
    },
    {
        id: 19,
        title: '轻盈一夏慢碳水套餐全麦荞麦面鸡胸肉丸全麦面包黑咖啡肉肠',
        image: '/goods/goods19/img_01.jpg',
        price: 39.9,
        originPrice: null,
        promotion: null,
    },
    {
        id: 20,
        title: '【2个装】现代简约浮雕纹玻璃花瓶透明鲜花插花瓶冰川纹',
        image: '/goods/goods20/img_01.jpg',
        price: 9.9,
        originPrice: null,
        promotion: null,
    },
];



    id: number;
    name: string;
    image: string;
}

const MOCK_TOP10CATEGORY = [
    { id: 1, name: '潮流买手店', image: '/goods/top10/top1.jpg' },
    { id: 2, name: '新趋势', image: '/goods/top10/top2.jpg' },
    { id: 3, name: '福利社', image: '/goods/top10/top3.jpg' },
    { id: 4, name: '小绿洲', image: '/goods/top10/top4.jpg' },
    { id: 5, name: '宝藏好店', image: '/goods/top10/top5.jpg' },
    { id: 6, name: '独特设计', image: '/goods/top10/top6.jpg' },
    { id: 7, name: '芭蕾风女孩', image: '/goods/top10/top7.jpg' },
    { id: 8, name: '清幽茶木香', image: '/goods/top10/top8.jpg' },
    { id: 9, name: '踏青必备', image: '/goods/top10/top9.jpg' },
    { id: 10, name: '青春出行', image: '/goods/top10/to10.jpg' },
];

    id: number;
    name: string;
    avatarUrl: string;
    lastMessage?: string;
    lastMessageTime?: string;
}

const MOCK_MESSAGE = [
    {
        id: 1,
        name: '春游起飞小组',
        avatarUrl: '/avatar/avatar_13.png',
        lastMessage: '你们到了没啊，我都等好久了',
        lastMessageTime: '昨天',
    },
    {
        id: 2,
        name: '手游组团菜鸡组',
        avatarUrl: '/avatar/avatar_14.png',
        lastMessage: '连跪三把，赢一把睡觉',
        lastMessageTime: '前天',
    },
    {
        id: 3,
        name: '抄作业小分队',
        avatarUrl: '/avatar/avatar_15.png',
        lastMessage: '数学物理还没写呢',
        lastMessageTime: '星期四',
    },
    {
        id: 4,
        name: '开心每一天',
        avatarUrl: '/avatar/avatar_16.png',
        lastMessage: null,
        lastMessageTime: null,
    },
    {
        id: 5,
        name: '高二16班',
        avatarUrl: '/avatar/avatar_17.png',
        lastMessage: '昨天卫生是谁值班的？给我站出来',
        lastMessageTime: '星期三',
    },
    {
        id: 6,
        name: '闺蜜群',
        avatarUrl: '/avatar/avatar_18.png',
        lastMessage: '这是谁的男朋友啊，好帅啊！',
        lastMessageTime: '星期三',
    },
    {
        id: 7,
        name: '团购水果链接分享群',
        avatarUrl: '/avatar/avatar_19.png',
        lastMessage: '最新的草莓到了，速来不等',
        lastMessageTime: '03-08',
    },
    {
        id: 8,
        name: '张小强',
        avatarUrl: '/avatar/avatar_20.png',
        lastMessage: '我跟你表白好几次了，你什么时候答应我啊',
        lastMessageTime: '03-07',
    },
    {
        id: 9,
        name: '互赞互粉小组006',
        avatarUrl: '/avatar/avatar_21.png',
        lastMessage: '我快2000粉了，大家加油',
        lastMessageTime: '03-06',
    },
    {
        id: 10,
        name: '王者荣耀组排',
        avatarUrl: '/avatar/avatar_22.png',
        lastMessage: '谁来带我飞啊，我已经被虐成狗了',
        lastMessageTime: '03-05',
    },
    {
        id: 11,
        name: '读书分享会',
        avatarUrl: '/avatar/avatar_23.png',
        lastMessage: null,
        lastMessageTime: null,
    },
    {
        id: 12,
        name: '考试复习分享',
        avatarUrl: '/avatar/avatar_24.png',
        lastMessage: '要被你们卷死了，你们太厉害了',
        lastMessageTime: '03-01',
    },
    {
        id: 13,
        name: '家人们',
        avatarUrl: '/avatar/avatar_25.png',
        lastMessage: null,
        lastMessageTime: null,
    },
    {
        id: 14,
        name: '随心聊瞎聊群',
        avatarUrl: '/avatar/avatar_26.png',
        lastMessage: '什么情况？我都不知道你们在说什么',
        lastMessageTime: '02-28',
    },
];

module.exports = { MOCK_USERS, MOCK_ARTICLES, MOCK_GOODS, MOCK_TOP10CATEGORY, MOCK_MESSAGE };
